// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: onos/ransim/metrics/metrics.proto

#include "onos/ransim/metrics/metrics.pb.h"
#include "onos/ransim/metrics/metrics.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace onos {
namespace ransim {
namespace metrics {

static const char* MetricsService_method_names[] = {
  "/onos.ransim.metrics.MetricsService/List",
  "/onos.ransim.metrics.MetricsService/Set",
  "/onos.ransim.metrics.MetricsService/Get",
  "/onos.ransim.metrics.MetricsService/Delete",
  "/onos.ransim.metrics.MetricsService/DeleteAll",
  "/onos.ransim.metrics.MetricsService/Watch",
};

std::unique_ptr< MetricsService::Stub> MetricsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MetricsService::Stub> stub(new MetricsService::Stub(channel, options));
  return stub;
}

MetricsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_List_(MetricsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(MetricsService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(MetricsService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(MetricsService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteAll_(MetricsService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Watch_(MetricsService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MetricsService::Stub::List(::grpc::ClientContext* context, const ::onos::ransim::metrics::ListRequest& request, ::onos::ransim::metrics::ListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::onos::ransim::metrics::ListRequest, ::onos::ransim::metrics::ListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_List_, context, request, response);
}

void MetricsService::Stub::async::List(::grpc::ClientContext* context, const ::onos::ransim::metrics::ListRequest* request, ::onos::ransim::metrics::ListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::onos::ransim::metrics::ListRequest, ::onos::ransim::metrics::ListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_List_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::List(::grpc::ClientContext* context, const ::onos::ransim::metrics::ListRequest* request, ::onos::ransim::metrics::ListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_List_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::ListResponse>* MetricsService::Stub::PrepareAsyncListRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::ListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::onos::ransim::metrics::ListResponse, ::onos::ransim::metrics::ListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_List_, context, request);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::ListResponse>* MetricsService::Stub::AsyncListRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::ListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::Set(::grpc::ClientContext* context, const ::onos::ransim::metrics::SetRequest& request, ::onos::ransim::metrics::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::onos::ransim::metrics::SetRequest, ::onos::ransim::metrics::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void MetricsService::Stub::async::Set(::grpc::ClientContext* context, const ::onos::ransim::metrics::SetRequest* request, ::onos::ransim::metrics::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::onos::ransim::metrics::SetRequest, ::onos::ransim::metrics::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::Set(::grpc::ClientContext* context, const ::onos::ransim::metrics::SetRequest* request, ::onos::ransim::metrics::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::SetResponse>* MetricsService::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::onos::ransim::metrics::SetResponse, ::onos::ransim::metrics::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::SetResponse>* MetricsService::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::Get(::grpc::ClientContext* context, const ::onos::ransim::metrics::GetRequest& request, ::onos::ransim::metrics::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::onos::ransim::metrics::GetRequest, ::onos::ransim::metrics::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void MetricsService::Stub::async::Get(::grpc::ClientContext* context, const ::onos::ransim::metrics::GetRequest* request, ::onos::ransim::metrics::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::onos::ransim::metrics::GetRequest, ::onos::ransim::metrics::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::Get(::grpc::ClientContext* context, const ::onos::ransim::metrics::GetRequest* request, ::onos::ransim::metrics::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::GetResponse>* MetricsService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::onos::ransim::metrics::GetResponse, ::onos::ransim::metrics::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::GetResponse>* MetricsService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::Delete(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteRequest& request, ::onos::ransim::metrics::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::onos::ransim::metrics::DeleteRequest, ::onos::ransim::metrics::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void MetricsService::Stub::async::Delete(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteRequest* request, ::onos::ransim::metrics::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::onos::ransim::metrics::DeleteRequest, ::onos::ransim::metrics::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::Delete(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteRequest* request, ::onos::ransim::metrics::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::DeleteResponse>* MetricsService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::onos::ransim::metrics::DeleteResponse, ::onos::ransim::metrics::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::DeleteResponse>* MetricsService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::DeleteAll(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteAllRequest& request, ::onos::ransim::metrics::DeleteAllResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::onos::ransim::metrics::DeleteAllRequest, ::onos::ransim::metrics::DeleteAllResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteAll_, context, request, response);
}

void MetricsService::Stub::async::DeleteAll(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteAllRequest* request, ::onos::ransim::metrics::DeleteAllResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::onos::ransim::metrics::DeleteAllRequest, ::onos::ransim::metrics::DeleteAllResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAll_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::DeleteAll(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteAllRequest* request, ::onos::ransim::metrics::DeleteAllResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAll_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::DeleteAllResponse>* MetricsService::Stub::PrepareAsyncDeleteAllRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteAllRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::onos::ransim::metrics::DeleteAllResponse, ::onos::ransim::metrics::DeleteAllRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteAll_, context, request);
}

::grpc::ClientAsyncResponseReader< ::onos::ransim::metrics::DeleteAllResponse>* MetricsService::Stub::AsyncDeleteAllRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::DeleteAllRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteAllRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::onos::ransim::metrics::WatchResponse>* MetricsService::Stub::WatchRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::WatchRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::onos::ransim::metrics::WatchResponse>::Create(channel_.get(), rpcmethod_Watch_, context, request);
}

void MetricsService::Stub::async::Watch(::grpc::ClientContext* context, const ::onos::ransim::metrics::WatchRequest* request, ::grpc::ClientReadReactor< ::onos::ransim::metrics::WatchResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::onos::ransim::metrics::WatchResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Watch_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::onos::ransim::metrics::WatchResponse>* MetricsService::Stub::AsyncWatchRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::WatchRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::onos::ransim::metrics::WatchResponse>::Create(channel_.get(), cq, rpcmethod_Watch_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::onos::ransim::metrics::WatchResponse>* MetricsService::Stub::PrepareAsyncWatchRaw(::grpc::ClientContext* context, const ::onos::ransim::metrics::WatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::onos::ransim::metrics::WatchResponse>::Create(channel_.get(), cq, rpcmethod_Watch_, context, request, false, nullptr);
}

MetricsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::onos::ransim::metrics::ListRequest, ::onos::ransim::metrics::ListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::onos::ransim::metrics::ListRequest* req,
             ::onos::ransim::metrics::ListResponse* resp) {
               return service->List(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::onos::ransim::metrics::SetRequest, ::onos::ransim::metrics::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::onos::ransim::metrics::SetRequest* req,
             ::onos::ransim::metrics::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::onos::ransim::metrics::GetRequest, ::onos::ransim::metrics::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::onos::ransim::metrics::GetRequest* req,
             ::onos::ransim::metrics::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::onos::ransim::metrics::DeleteRequest, ::onos::ransim::metrics::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::onos::ransim::metrics::DeleteRequest* req,
             ::onos::ransim::metrics::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::onos::ransim::metrics::DeleteAllRequest, ::onos::ransim::metrics::DeleteAllResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::onos::ransim::metrics::DeleteAllRequest* req,
             ::onos::ransim::metrics::DeleteAllResponse* resp) {
               return service->DeleteAll(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MetricsService::Service, ::onos::ransim::metrics::WatchRequest, ::onos::ransim::metrics::WatchResponse>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::onos::ransim::metrics::WatchRequest* req,
             ::grpc::ServerWriter<::onos::ransim::metrics::WatchResponse>* writer) {
               return service->Watch(ctx, req, writer);
             }, this)));
}

MetricsService::Service::~Service() {
}

::grpc::Status MetricsService::Service::List(::grpc::ServerContext* context, const ::onos::ransim::metrics::ListRequest* request, ::onos::ransim::metrics::ListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::Set(::grpc::ServerContext* context, const ::onos::ransim::metrics::SetRequest* request, ::onos::ransim::metrics::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::Get(::grpc::ServerContext* context, const ::onos::ransim::metrics::GetRequest* request, ::onos::ransim::metrics::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::Delete(::grpc::ServerContext* context, const ::onos::ransim::metrics::DeleteRequest* request, ::onos::ransim::metrics::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::DeleteAll(::grpc::ServerContext* context, const ::onos::ransim::metrics::DeleteAllRequest* request, ::onos::ransim::metrics::DeleteAllResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::Watch(::grpc::ServerContext* context, const ::onos::ransim::metrics::WatchRequest* request, ::grpc::ServerWriter< ::onos::ransim::metrics::WatchResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace onos
}  // namespace ransim
}  // namespace metrics

